print("Введите вид питомца: ")
species = input()
print("Введите кличку питомца: ")
name = input()
print("Введите возраст питомца: ")
age = input()
print("Это " + species + " по кличке \"" + name + "\". Возраст: " + age + " года.")