print("Введите число N (количество чисел в строке): ")
number = int(input())
print("Введите через пробел N чисел")
tmp = list(input().split())

print("Массив, который вы ввели: ")
print(*tmp)
print("Измененный массив: ")
print(*tmp[-1], end='')
print(' ', end='')
print(*tmp[0:-1:])
