print("Введите число N (кол-во чисел, которые вы будете вводить позже): ")
number = int(input())
print("Введите через пробел N чисел: ")
tmp = map(int, input().split())
arr = set(tmp)
print("Количество различных чисел среди введенных: ")
print(len(arr))